#!/bin/sh

dir=${1:-~/Downloads/bootstrap}

cp -f $dir/css/bootstrap*.min.css css
cp -f $dir/js/bootstrap.min.js js
cp -f $dir/config.json bootstrap-config.json
chmod -R -x css/* js/* bootstrap-config.json
