#!/bin/bash

set -e

mkdir -p assets

templates() {
  handlebars -p templates/partials/*.handlebars
  handlebars templates/*.handlebars
}

uglifyjs --source-map assets/main.min.js.map -c -m -- bootstrap/bootstrap.min.js <(templates) js/data.js js/ui.js > assets/main.min.js

cat bootstrap/bootstrap.min.css bootstrap/bootstrap-theme.min.css <(cat style.styl | stylus) | cleancss -O1 specialComments:0 -o assets/style.css --source-map
