#!/bin/bash

set -e

mkdir -p assets

templates() {
  handlebars -p templates/partials/*.handlebars
  handlebars templates/*.handlebars
}

uglifyjs --source-map assets/main.min.js.map -c -m -- bootstrap/bootstrap.min.js <(templates) js/data.js js/ui.js > assets/main.min.js

stylus -c --include-css -o assets/style.css style.styl
